### ISSUE TITLE
Currently doesn't work with more complex redox reactions: 

### ISSUE THREAD

**Issue by markaaen** [Sumit-Dey-2002/Redox-Reaction-Balancer#1]
Hi guys,

I'm trying to balance out the following redox reaction: 

FeO2(s) + H2S(aq) --> Fe^2+(aq)  + SO4^2-(aq)  in a water-based acidic solution however i get an index error saying list index is out of range.

My reaction declaration is the following line:

reaction = Reaction('(1)Fe1O2[0] + (1)H2S[0]', '(1)Fe[+2] + (1)S1O4[-2]')

Any fixes? 

Best, M

**Comment by shba007** [comment]
The reaction should be

### FeO2(s) + H2S(aq) --> Fe2+(aq) + SO42-(aq)
reaction = Reaction('(1)Fe1O2[0] + (1)H2S1[0]', '(1)Fe1[+2] + (1)S1O4[-2]')

you missed the 1 in H2S1 and 1 in Fe1
